### ISSUE TITLE
python package import issue

### ISSUE THREAD

**Issue by krishnakumarq** [conda-forge/libgdal-feedstock#44]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/__main__.py", line 12, in <module>
    from azure.cli.core import get_default_cli
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 12, in <module>
    from pkg_resources import parse_version
  File "/usr/lib64/az/lib/python2.7/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import email.parser
  File "/usr/lib64/python2.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser
  File "/usr/lib64/python2.7/email/feedparser.py", line 27, in <module>
    from email import message
  File "/usr/lib64/python2.7/email/message.py", line 16, in <module>
    import email.charset
  File "/usr/lib64/python2.7/email/charset.py", line 13, in <module>
    import email.base64mime
  File "/usr/lib64/python2.7/email/base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "/usr/lib64/python2.7/email/utils.py", line 27, in <module>
    import random
  File "/usr/lib64/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/usr/lib64/python2.7/hashlib.py", line 116, in <module>
    import _hashlib
ImportError: /usr/lib64/libgssapi_krb5.so.2: symbol k5_buf_free, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference

**Comment by krishnakumarq** [comment]
Can Any one please help on this!!!!!

**Comment by ocefpaf** [comment]
All your errors are coming from `/usr/lib64/` looks like you have a problem with your system installation and not `conda-forge`.

[Here is one of many instructions on how to get started with conda/miniconda](http://ioos.github.io/notebooks_demos/other_resources/). I also recommend you to take a look at Anaconda and its docs. And [here is some conda-forge docs that may help you.](https://conda-forge.org/docs/conda-forge_gotchas.html)
