### ISSUE TITLE
krb5 is wrongly linked to system version of library.

### ISSUE THREAD

**Issue by cpaulik** [conda-forge/libgdal-feedstock#9]
We have the following problem on one of our machines. Older environments using older gdal versions of conda-forge worked without issue so I'm wondering if this is an issue with the package or conda-build. I will also raise an issue for conda-build because of the conda inspect warning.

### Installation and Error
```
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
bash Miniconda2-latest-Linux-x86_64.sh 
source .bashrc
conda update conda
conda create -n test1 -c conda-forge python=2 gdal
source activate test1
python -c "import osgeo"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lv70533/cpa/miniconda2/envs/test1/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/lv70533/cpa/miniconda2/envs/test1/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: /usr/lib64/libkrb5.so.3: symbol krb5int_labeled_open, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference
```

### conda inspect

`conda inspect linkages gdal` gives me the following:

#### Warning:
```
WARNING: pyldd disagrees with ldd/otool. This will not cause any
WARNING: problems for this build, but please file a bug at:
WARNING: https://github.com/conda/conda-build
WARNING: and (if possible) attach file /home/lv70533/cpa/miniconda2/envs/test1/lib/python2.7/site-packages/osgeo/_ogr.so
```
#### Output:
```
curl-7.54.1-0:
    libcurl.so.4 (lib/libcurl.so.4)

expat-2.2.1-0:
    libexpat.so.1 (lib/libexpat.so.1)

freexl-1.0.2-2:
    libfreexl.so.1 (lib/libfreexl.so.1)

geos-3.5.1-1:
    libgeos-3.5.1.so (lib/libgeos-3.5.1.so)
    libgeos_c.so.1 (lib/libgeos_c.so.1)

giflib-5.1.4-0:
    libgif.so.7 (lib/libgif.so.7)

hdf4-4.2.12-0:
    libdf.so.0 (lib/libdf.so.0)
    libmfhdf.so.0 (lib/libmfhdf.so.0)

hdf5-1.8.18-1:
    libhdf5.so.10 (lib/libhdf5.so.10)
    libhdf5_cpp.so.13 (lib/libhdf5_cpp.so.13)
    libhdf5_hl.so.10 (lib/libhdf5_hl.so.10)

icu-58.1-1:
    libicudata.so.58 (lib/libicudata.so.58)
    libicui18n.so.58 (lib/libicui18n.so.58)
    libicuuc.so.58 (lib/libicuuc.so.58)

jpeg-9b-0:
    libjpeg.so.9 (lib/libjpeg.so.9)

json-c-0.12.1-0:
    libjson-c.so.2 (lib/libjson-c.so.2)

kealib-1.4.7-2:
    libkea.so.1.4.7 (lib/libkea.so.1.4.7)

krb5-1.14.2-0:
    libcom_err.so.3 (lib/libcom_err.so.3)
    libkrb5support.so.0 (lib/libkrb5support.so.0)

libdap4-3.18.3-2:
    libdap.so.23 (lib/libdap.so.23)
    libdapclient.so.6 (lib/libdapclient.so.6)
    libdapserver.so.7 (lib/libdapserver.so.7)

libgdal-2.2.1-0:
    libgdal.so.20 (lib/libgdal.so.20)

libiconv-1.14-4:
    libcharset.so.1 (lib/libcharset.so.1)
    libiconv.so.2 (lib/libiconv.so.2)

libnetcdf-4.4.1.1-6:
    libnetcdf.so.11 (lib/libnetcdf.so.11)

libpng-1.6.28-1:
    libpng16.so.16 (lib/libpng16.so.16)

libpq-9.6.3-0:
    libpq.so.5 (lib/libpq.so.5)

libspatialite-4.3.0a-15:
    libspatialite.so.7 (lib/libspatialite.so.7)

libtiff-4.0.6-7:
    libtiff.so.5 (lib/libtiff.so.5)

libxml2-2.9.4-4:
    libxml2.so.2 (lib/libxml2.so.2)

openjpeg-2.2.0-0:
    libopenjp2.so.7 (lib/libopenjp2.so.7)

openssl-1.0.2l-0:
    libcrypto.so.1.0.0 (lib/libcrypto.so.1.0.0)
    libssl.so.1.0.0 (lib/libssl.so.1.0.0)

proj4-4.9.3-4:
    libproj.so.12 (lib/libproj.so.12)

python-2.7.13-1:
    libpython2.7.so.1.0 (lib/libpython2.7.so.1.0)

sqlite-3.13.0-1:
    libsqlite3.so.0 (lib/libsqlite3.so.0)

util-linux-2.21-0:
    libuuid.so.1 (lib/libuuid.so.1)

xerces-c-3.1.4-3:
    libxerces-c-3.1.so (lib/libxerces-c-3.1.so)

xz-5.2.3-0:
    liblzma.so.5 (lib/liblzma.so.5)

zlib-1.2.8-3:
    libz.so.1 (lib/libz.so.1)

system:
    libc.so.6 (/usr/lib64/libc.so.6)
    libcom_err.so.2 (/usr/lib64/libcom_err.so.2)
    libcrypto.so.10 (/usr/lib64/libcrypto.so.10)
    libdl.so.2 (/usr/lib64/libdl.so.2)
    libgcc_s.so.1 (/usr/lib64/libgcc_s.so.1)
    libgssapi_krb5.so.2 (/usr/lib64/libgssapi_krb5.so.2)
    libk5crypto.so.3 (/usr/lib64/libk5crypto.so.3)
    libkeyutils.so.1 (/usr/lib64/libkeyutils.so.1)
    libkrb5.so.3 (/usr/lib64/libkrb5.so.3)
    libm.so.6 (/usr/lib64/libm.so.6)
    libpthread.so.0 (/usr/lib64/libpthread.so.0)
    libresolv.so.2 (/usr/lib64/libresolv.so.2)
    librt.so.1 (/usr/lib64/librt.so.1)
    libssh2.so.1 (/usr/lib64/libssh2.so.1)
    libssl.so.10 (/usr/lib64/libssl.so.10)
    libstdc++.so.6 (/usr/lib64/libstdc++.so.6)
    libutil.so.1 (/usr/lib64/libutil.so.1)
    linux-vdso.so.1 ()
```

### Environment
This is the environment I end up with after the installation:
```
name: test1
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py27_0
- curl=7.54.1=0
- expat=2.2.1=0
- freexl=1.0.2=2
- gdal=2.2.1=np113py27_0
- geos=3.5.1=1
- giflib=5.1.4=0
- hdf4=4.2.12=0
- hdf5=1.8.18=1
- icu=58.1=1
- jpeg=9b=0
- json-c=0.12.1=0
- kealib=1.4.7=2
- krb5=1.14.2=0
- libdap4=3.18.3=2
- libgdal=2.2.1=0
- libiconv=1.14=4
- libnetcdf=4.4.1.1=6
- libpng=1.6.28=1
- libpq=9.6.3=0
- libspatialite=4.3.0a=15
- libssh2=1.8.0=1
- libtiff=4.0.6=7
- libxml2=2.9.4=4
- ncurses=5.9=10
- openjpeg=2.2.0=0
- openssl=1.0.2l=0
- pip=9.0.1=py27_0
- proj4=4.9.3=4
- python=2.7.13=1
- readline=6.2=0
- setuptools=36.2.2=py27_0
- sqlite=3.13.0=1
- tk=8.5.19=2
- wheel=0.29.0=py27_0
- xerces-c=3.1.4=3
- xz=5.2.3=0
- zlib=1.2.8=3
- libgfortran=3.0.0=1
- mkl=2017.0.3=0
- numpy=1.13.1=py27_0
- util-linux=2.21=0
```

**Comment by gillins** [comment]
@ocefpaf should `krb5` be a runtime dependency of `gdal`?

**Comment by ocefpaf** [comment]
@gillins that was probably a hack from early days to force `conda` to solve the dependencies correctly. We lost the opportunity to remove it [here](https://github.com/conda-forge/gdal-feedstock/pull/84).

I guess we should try to remove it again.

**Comment by gillins** [comment]
> I guess we should try to remove it again.

You mean add it again? It seems something in `gdal` is pulling it in so we would be best to supply the conda-forge implementation rather than depend on a (possibly old) system implementation. I'm not sure why I was trying to remove `krb5` in that PR.... Maybe it wasn't needed back then?

**Comment by ocefpaf** [comment]
> You mean add it again?

Sorry, I was not clear. I thought that we were still adding the dependency there to ensure the conda-forge version would be picked up.

>  It seems something in `gdal` is pulling it in so we would be best to supply the conda-forge implementation rather than depend on a (possibly old) system implementation. I'm not sure why I was trying to remove `krb5` in that PR.... Maybe it wasn't needed back then?

`krb5` is used in `curl` and the linkages look fine.

@cpaulik I'll take a closer look at the resulting environment tomorrow too see if I can find what is going on. Just to be sure you only get that with `gdal 2.2.1`, right?

**Comment by gillins** [comment]
> krb5 is used in curl and the linkages look fine.

Yes you are right, sorry. Not sure what is going on...

**Comment by cpaulik** [comment]
After a little more investigation I found that the admins of this machine set
```
LD_LIBRARY_PATH=":/usr/lib:/usr/lib64:/lib:/lib64:/cm/shared/apps/slurm/current/lib:/cm/shared/apps/slurm/current/lib/slurm"
```
removing this environment variable fixes the problem.

So I guess everything is fine with the gdal package.
